import type { Snapshot, Entry } from "./schema.js";

const business: Entry[] = [
  ["monthly-camp", "社会创新月月营", "youth"],
  ["international-camp", "国际社会创新研学营", "youth"],
  ["public-speaking", "演讲与表达", "youth"],
  ["ai-and-theme-courses", "AI+与主题课程", "youth"],
  ["youth-practice", "大学生与青年实践", "youth"],
  ["volunteering", "企业志愿者服务", "corporate"],
  ["csr-consulting", "CSR与公益咨询", "corporate"],
  ["cross-border", "企业出海与跨文化支持", "corporate"],
  ["resilience", "员工心理韧性建设", "corporate"],
  ["organization-development", "组织发展与导师制", "corporate"],
].map(([slug, title, segment], index) => ({
  id: `business-${slug}`,
  kind: "business" as const,
  slug,
  title,
  segment: segment as "youth" | "corporate",
  summary: "此方向的公开服务范围与具体安排将在审核后更新。",
  bodyHtml: `<p>${title}的服务说明正在审核中，欢迎先与团队沟通实际需求。</p>`,
  approved: false,
  order: index + 1,
}));
export const previewSnapshot: Snapshot = {
  version: "preview-fixture",
  generatedAt: new Date(0).toISOString(),
  mode: "preview",
  company: {
    name: "Empact China",
    legalName: "",
    description: "连接青年实践与组织协作的社会创新服务团队。",
    email: "",
    approved: false,
    privacyApproved: false,
    contactEnabled: false,
    retentionDays: 30,
  },
  entries: [
    {
      id: "home",
      kind: "page",
      slug: "home",
      title: "Empact China",
      summary: "连接青年实践与组织协作，探索面向真实议题的社会创新。",
      bodyHtml:
        "<p>从青少年与青年实践，到企业合作与组织支持，Empact China 正在整理可公开的服务信息。</p>",
      approved: false,
    },
    {
      id: "youth",
      kind: "page",
      slug: "youth",
      title: "青少年项目",
      summary: "面向青少年与青年的学习、表达与实践方向。",
      bodyHtml: "<p>具体项目安排以审核后公布的信息为准。</p>",
      approved: false,
    },
    {
      id: "corporate",
      kind: "page",
      slug: "corporate",
      title: "企业服务",
      summary: "围绕企业公益、跨文化和组织支持的合作方向。",
      bodyHtml: "<p>团队将根据实际合作需求提供进一步说明。</p>",
      approved: false,
    },
    {
      id: "about",
      kind: "page",
      slug: "about",
      title: "关于 Empact",
      summary: "了解团队正在开展的服务方向与合作方式。",
      bodyHtml: "<p>公司主体与公开资料将在完成审核后展示。</p>",
      approved: false,
    },
    {
      id: "privacy",
      kind: "page",
      slug: "privacy",
      title: "隐私政策",
      summary: "了解我们如何处理信息。",
      bodyHtml: "<p>我们仅在必要范围内处理信息。</p>",
      approved: false,
    },
    {
      id: "terms",
      kind: "page",
      slug: "terms",
      title: "使用条款",
      summary: "网站使用条款。",
      bodyHtml: "<p>请在使用服务前阅读本条款。</p>",
      approved: false,
    },
    {
      id: "contact",
      kind: "page",
      slug: "contact",
      title: "联系我们",
      summary: "联系 Empact China。",
      bodyHtml: "<p>欢迎通过公开联系方式与我们沟通。</p>",
      approved: false,
    },
    {
      id: "chatcircle",
      kind: "project",
      slug: "chatcircle",
      title: "ChatCircle",
      summary: "一个仍在整理公开材料的公益对话项目。",
      bodyHtml:
        "<p>ChatCircle 的项目介绍、参与方式和平台链接将在取得审核材料后更新。</p>",
      approved: false,
      projectStatus: "consultation",
      audience: "青年",
      operator: "Empact China",
    },
    ...business,
  ],
  media: [],
};
